### ISSUE TITLE
Allow using a virtual FS

### ISSUE THREAD

**Issue by aphistic** [go-nacelle/config#1]
It would be useful to be able to swap out the FS methods using something like https://github.com/spf13/afero, specifically the `FileSourcer`.  We're planning to use https://www.telepresence.io/ for local development and in order to be able to find files it needs to somehow remap the root FS to the remotely mounted FS from the cluster.  Being able to give it a FS object with that as the root would make it a lot easier to implement (and potentially easier to test)!

**Comment by efritz** [comment]
Done via #2, available in 1.1.0.
